* Julia-Box-Shell 
** Overview 

Docker for Julia language with X11 (User Interface) support and  many
pre-installed packages and wrapper script for running the docker. 

 *Benefit* 

  + A ready-to-use Julia development environment, with zero
    configuration required, in a Box which can be used from any Linux
    distribution or any operating system with Docker support.

 *Features*

   * Many pre-installed packages for statics, charts, symbolic math
     and so on.

   * Julia Notebook
     + Jupyter Notebook for Julia. 

   * X11 Support
     + Allows to run graphical windows and GUIs (Graphical User
       Interfaces) such as X11 widgets, PyPlot charts, Plots chart
       and so on.

   * Wrapper Unix shell script which simplifies running the docker and
     mapping the current directory to the docker container. 

 *Pre-installed packages*

  * Interfaces
    * IJulia => Julia Notebook 

  * Plot libraries
    + Plots
    + PyPlot
    + StatsPlot

  * Statistcs:
    + Distributions => Statistical Distributions 
    + DataFrame
    + DataStreams

  * Standard Format Parsers 
    + JSON
    + CSV
    + XLSX - Excel Parser

  * Symbolic Math
    + SymPy
** Usage 

STEP 1: Build the docker. 

#+BEGIN_SRC sh 
  $ make build 
#+END_SRC

STEP 2: Test the docker with. The command will run a Julia shell. 

#+BEGIN_SRC python 
  $ make run
  sh ./julia-box-shell.sh
  non-network local connections being added to access control list
                 _
     _       _ _(_)_     |  Documentation: https://docs.julialang.org
    (_)     | (_) (_)    |
     _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
    | | | | | | |/ _` |  |
    | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
   _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
  |__/                   |

  julia> 0:2:10 .|> exp(x)
  ERROR: UndefVarError: x not defined
  Stacktrace:
   [1] top-level scope at REPL[1]:1

  julia> 0:2:10 .|> exp
  6-element Array{Float64,1}:
       1.0              
       7.38905609893065 
      54.598150033144236
     403.4287934927351  
    2980.9579870417283  
   22026.465794806718   
#+END_SRC

STEP 3: Install the wrapper script. 
   + Just copy the wrapper script to any directory in $PATH variable
     and run $ julia-box-shell.sh 

#+BEGIN_SRC sh 
  mkdir -p ~/bin 
  chmod +x julia-box-shell.sh 
  cp julia-box-shell.sh ~/bin 

  # If the directory ~/bin is not in the PATH variable. 
  echo "export PATH=~/bin:$PATH" >> ~/.bashrc 
#+END_SRC

STEP 4: Run wrapper script and open Julia shell. 

#+BEGIN_SRC sh 
  $ sh julia-box-shell.sh 

  non-network local connections being added to access control list
                 _
     _       _ _(_)_     |  Documentation: https://docs.julialang.org
    (_)     | (_) (_)    |
     _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
    | | | | | | |/ _` |  |
    | | |_| | | | (_| |  |  Version 1.3.1 (2019-12-30)
   _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
  |__/                   |

  julia> using SymPy

  julia> x = Sym("x")
  x

  julia> expand((x - 4)^3)
   3       2            
  x  - 12⋅x  + 48⋅x - 64
#+END_SRC
